name: Deploy to OZ on Push or Merge to Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy-to-oz:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run deploy to OZ script
        run: node deploy.js
        env:
          DEFENDER_API_KEY: ${{ secrets.DEFENDER_API_KEY }}
          DEFENDER_API_SECRET: ${{ secrets.DEFENDER_API_SECRET }}
